apiVersion: apps/v1
kind: Deployment
metadata:
  name: myd
  labels:
    app: cycle
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cycle
  template:
    metadata:
      labels:
        app: cycle
    spec:
      containers:
        - name: cont8
          image: yaseenbasha/basha
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc7
spec:
  type: NodePort
  selector:
    app: cycle
  ports:
    - port: 80
      targetPort: 80

