apiVersion: apps/v1
kind: Deployment
metadata:
  name: msyd
  labels:
    app: basha
spec:
  replicas: 4
  selector:
    matchLabels:
      app: basha
  template:
    metadata:
      labels:
        app: basha
    spec:
      containers:
        - name: cont8
          image: yaseenbasha/basha
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc9
spec:
  type: NodePort
  selector:
    app: basha
  ports:
    - port: 80
      targetPort: 80

